# Generated by Django 5.1.7 on 2025-03-30 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_method', models.CharField(choices=[('delivery', 'Delivery'), ('dropoff', 'Dropoff')], default='delivery', max_length=20)),
                ('donation_date', models.DateField()),
                ('donation_time', models.TimeField(default=django.utils.timezone.now)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_range', models.CharField(blank=True, choices=[('<5', 'Less than 5kg'), ('5-10', '5 to 10kg'), ('10-20', '10 to 20kg'), ('20+', 'More than 20kg')], max_length=10, null=True)),
                ('dropoff_location', models.CharField(blank=True, choices=[('location1', 'Location 1'), ('location2', 'Location 2')], max_length=50, null=True)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('household', 'Household'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('toys', 'Toys'), ('stationery', 'Stationery')], default='household', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('intended_action', models.CharField(choices=[('donation', 'Donation'), ('recycling', 'Recycling')], default='donation', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('pending_cancellation', 'Pending Cancellation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('verification_comment', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donations.donation')),
            ],
        ),
    ]
